---
# tasks file for elasticsearch
- name: Add Elasticsearch GPG key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repo
  yum_repository:
    name: elasticsearch-6.x
    description: Elasticsearch repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Install Elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: Make elasticsearch only listen to localhost
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "^#?network.host:"
    line: "network.host: localhost"

- name: Start elasticsearch
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
    daemon_reexec: yes
